### ISSUE TITLE
Warning: jsdoc failure Used --force, continuing

### ISSUE THREAD

**Issue by srad** [krampstudio/grunt-jsdoc#109] opened 2014-12-19 15:49 UTC
I get the following error message when running grunt on Windows 8.1:
```
Running "jsdoc:build" (jsdoc) task
>> An error occurs in jsdoc process:
>> Die Befehlszeile ist zu lang. (Command is too long)
Warning: jsdoc failure Used --force, continuing.
>> jsdoc terminated
Warning: jsdoc failure Used --force, continuing.
```
I don't use any special configuration, it's straight from the readme. I saw you had couple similar issues regarding this error in the past. Anybody knows what's going on here?

gruntfile:
```
    jsdoc:  {
            build: {
                src:     ['js/src/**/*.js'],
                options: {
                    destination: 'js/build/doc'
                }
            }
        },
```

The doc folder is created but the files not generated.

**Comment by jdoose** [comment] 2015-01-25 09:29
propably duplicate of #95, since it is the same error message?

**Comment by krampstudio** [comment] 2015-05-27 11:30
The issue is that grunt file sources are expanded and then I add them to the command.
On windows system the length of the command is limited. 
If you want to handle a large bunch of files, I suggest you to create a jsdoc config file (see http://usejsdoc.org/about-configuring-jsdoc.html) and omit the `src` option in the gruntfile and set the `source` field in the jsdoc config.

```javascript
jsdoc:  {
            build: {
                options: {
                    destination: 'js/build/doc',
                    configure : 'path/to/jsdoc.conf.json' 
                }
            }
        }
```

**Closed** 2015-05-27 11:33 UTC
